// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebSanadApplication.Models
{
    public partial class Get_New_Entry_NumberResult
    {
        public string ENTRY_NUMBER { get; set; }
        public long? COLLECT_ENTRY_CODE { get; set; }
    }
}
