// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebSanadApplication.Models
{
    public partial class MohamedContext : DbContext
    {

        public MohamedContext(DbContextOptions<MohamedContext> options)
            : base(options)
        {

        }
         
        public virtual DbSet<GET_ENTRY_SETTINGResult> GET_ENTRY_SETTINGResultasync { get; set; }=null!;
        public virtual DbSet<Get_New_Entry_NumberResult> Get_New_Entry_NumberResultasync { get; set; } = null;
        public virtual DbSet<SELECT_ALL_CURRENCIESResult> SELECT_ALL_CURRENCIESResultasync { get; set; } = null;
        public virtual DbSet<SEARCH_ACCOUNTSResult> SELECT_SEARCH_ACCOUNTSResult { get; set; } = null;
        
        /*
        Task<List<GET_ENTRY_SETTINGResult>>(short? ENTRY_SETTING_ID, string LANG);
        Task<List<Get_New_Entry_NumberResult>> Get_New_Entry_NumberAsync(int? ENTRY_SETTING_ID, int? SHIFT_NUMBER, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SELECT_ALL_CURRENCIESResult>> SELECT_ALL_CURRENCIESAsync(string LANG, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GET_ENTRY_SETTINGResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<Get_New_Entry_NumberResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SELECT_ALL_CURRENCIESResult>().HasNoKey().ToView(null);
        }
         */

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GET_ENTRY_SETTINGResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<Get_New_Entry_NumberResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SEARCH_ACCOUNTSResult>().HasNoKey().ToView(null);

            modelBuilder.Entity<SELECT_ALL_CURRENCIESResult>().HasNoKey().ToView(null);
        
            OnModelCreatingPartial(modelBuilder);
        }
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

   