// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>


using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace WebSanadApplication.Models
{
    public partial class SEARCH_ACCOUNTSResult
    {
        public int ACC_ID { get; set; }
        public string ACC_CODE { get; set; }
      

        public string ACC_AR_NAME { get; set; }
        public string ACC_EN_NAME { get; set; }
       public byte ACC_TYPE_ID { get; set; }
        public double? ACC_MAX_DEBIT { get; set; }
        public bool? ACC_MUST_COST_CENTER { get; set; }
    }
}
